stages:
  - build
  - test

variables:
  # Define variables as needed

build_gamedocker_image:
  stage: build
  script:
    - docker build -t gameserver -f Dockerfile.gameserver .
  only:
    - develop  # Adjust the branch name as needed
run_gamedocker_container:
  stage: test
  script:
    - docker run -d  8080:8080 gameserver $
  only:
    - develop  # Adjust the branch name as needed
build_authdocker_image:
  stage: build
  script:
    - docker build -t authserver -f Dockerfile.authserver .
  only:
    - develop 
run_authdocker_container:
  stage: test
  script:
    - docker run -d  8081:8081 authserver $
  only:
    - develop  # Adjust the branch name as needed

install_dependencies:
  stage: test
  script:
    - dart pub get
  only:
    - develop  # Adjust the branch name as needed

run_tests:
  stage: test
  script:
    - dart test test/server_test.dart
  only:
    - develop  # Adjust the branch name as needed