stages:
  - build
  - test

variables:
  # Define variables as needed

build_docker_image:
  stage: build
  image: docker:19.03.13
  script:
    - docker build -t tictactoeserver .
  only:
    - develop  # Adjust the branch name as needed

run_docker_container:
  stage: test
  script:
    - docker run -d -p 8080:8080 -p 8081:8081 tictactoeserver $
  only:
    - develop  # Adjust the branch name as needed

install_dependencies:
  stage: test
  script:
    - dart pub get
  only:
    - develop  # Adjust the branch name as needed

run_tests:
  stage: test
  script:
    - dart test test/server_test.dart
  only:
    - develop  # Adjust the branch name as needed