services:
  game :
    build:
      context: ./
      dockerfile: Dockerfile.gameserver
    ports : 
      - 8080:8080
  auth :
    build : 
       context: ./
       dockerfile: Dockerfile.authserver
    ports : 
      - 8081:8081

    