name: tic_tac_toe_server
description: A tictactoe server app .
version: 1.0.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  args: ^2.3.0
  crypt: ^4.3.1
  mongo_dart: ^0.9.3
  web_socket_channel: ^2.4.0
  webdev: ^2.7.12


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
