name: tic_tac_toe_server
description: A tictactoe server app .
version: 1.0.0

environment:
  sdk: '>=2.19.6'

dependencies:
  args: ^2.3.0
  crypt: ^4.3.1
  dart_jsonwebtoken: ^2.12.0
  dotenv: ^4.2.0
  http: ^1.2.1
  image: ^4.1.7
  mime: ^1.0.5
  mongo_dart: ^0.10.3
  shelf: ^1.4.1
  shelf_web_socket: ^2.0.0
  web_socket_channel: ^3.0.1






dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.8
