
previews:
  generation: automatic
services:
  - type: web
    name: image-server
    image: 
      url: docker.io/mohamedaminelili02/tictactoe:latest
    plan: standard  


  - type: web
    name: game-server
    image:
      url:  docker.io/mohamedaminelili02/tictactoe:latest  
    plan: standard  
    autoDeploy: true


  - type: web
    name: nginx
    image:
      url:   docker.io/mohamedaminelili02/tictactoe_nginx:latest 
    plan: standard 
    autoDeploy: true
