name: Dart Test

on:
  push:
    branches:
      - feature 

jobs:
  
     

 
      

  test:
      runs-on: ubuntu-latest

      steps:
        - uses: dart-lang/setup-dart@v1
        - uses: actions/checkout@v3
       
        - name: Build auth Container 
          run:  docker build  -t authserver -f Dockerfile.authserver .       
        
      
        - name: Build game Container
          run:  docker build  -t gameserver -f Dockerfile.gameserver .       
        
        - name: Run both containers
        
          
          run: docker-compose up &
          shell: bash



        - name: Install dependencies
          run: dart pub get
        

          
        - name: Run tests 
          run: dart test test/server_test.dart
          
            
         
 

        

        
     
    
 
  