name: Dart Test

on:
  push:
    branches:
      - develop  # Adjust the branch name as needed

jobs:
  
     

 
      

  test:
      runs-on: ubuntu-latest

      steps:
        - uses: dart-lang/setup-dart@v1
        - uses: actions/checkout@v3
       
        - name: Build Docker
          run:  docker build  -t tictactoeserver .       
        
        - name: Run Docker container 
        
          
          run: BG_PID=$! docker run -p 8080:8080 -p 8081:8081 tictactoeserver &
          shell: bash


        - name: Install dependencies
          run: dart pub get
        

        - name: Run tests
          run: dart test test/server_test.dart

        

        
     
    
 
  