name: Dart Test

on:
  push:
      

jobs:
  
     

 
      

  test:
      runs-on: ubuntu-latest

      steps:
        - uses: dart-lang/setup-dart@v1
        - uses: actions/checkout@v3
       
        - name: Build game Container
          run:  docker build  -t gameserver .   
        
        - name : install jemeter
          run:  wget -q "https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.1.zip" -P /tmp

        - name : install jemeter
          run: unzip -q "/tmp/apache-jmeter-5.4.1.zip" -d /opt
        - name : install jemeter
          run: echo $PATH

        - name: Run Container
        
          
          run: docker run -p 8080:8080  gameserver &
          shell: bash
        - name: Wait for Container
        
          
          run: sleep 15
          shell: bash


        - name: Install dependencies
          run: dart pub get
        

        - name:  load testing 
          run: /opt/apache-jmeter-5.4.1/bin/jmeter -n -t ./jmetertestplan.jmx -l results.jtl
        - name:  show load testing results
          run: cat results.jtl


        - name: Run tests 
          run: dart test test/server_test.dart
          
            
         
 

        

        
     
    
 
  