name: Dart Test

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  test:
      runs-on: ubuntu-latest

      steps:
        - uses: dart-lang/setup-dart@v1
        - uses: actions/checkout@v3

        - name: Install dependencies
          run: dart pub get

        - name: Run tests
          run: dart test sever_test.dart

# Add more steps as needed, such as deployment steps
