name: Dart Test

on:
  push:
    branches:
      - develop  # Adjust the branch name as needed

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    run: dart pub get
    run: dart test test/server_test.dart

# Add more steps as needed, such as deployment steps
