name: Dart Test

on:
  push:
    branches:
      - feature 

jobs:
  
     

 
      

  test:
      runs-on: ubuntu-latest

      steps:
        - uses: dart-lang/setup-dart@v1
        - uses: actions/checkout@v3
       
        - name: Build auth Container 
          run:  docker build  -t authserver -f Dockerfile.authserver .       
        
      
        - name: Build game Container
          run:  docker build  -t gameserver -f Dockerfile.gameserver .   
        
        - name : install jemeter
          run:  wget -q "https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.1.zip" -P /tmp

        - name : install jemeter
          run: unzip -q "/tmp/apache-jmeter-5.4.1.zip" -d /opt
        - name : install jemeter
          run:  export PATH=$PATH:/opt/apache-jmeter-5.4.1/bin

        
        
        - name: Run both containers
        
          
          run: docker-compose up &
          shell: bash



        - name: Install dependencies
          run: dart pub get
        

        - name:  jemeter testing 
          run: jmeter 
   


        - name: Run tests 
          run: dart test test/server_test.dart
          
            
         
 

        

        
     
    
 
  