name: Dart Test

on:
  push:
    branches:
      - develop  # Adjust the branch name as needed

jobs:
  build-and-test:
    steps:
      run: dart pub get

# Add more steps as needed, such as deployment steps
