name: Dart Test

on:
  push:
    branches:
      - feature  # Adjust the branch name as needed

jobs:
  build_container:
    runs-on: ubuntu-latest

    steps:
      - uses: dart-lang/setup-dart@v1
      - uses: actions/checkout@v3

      - name: Build Docker
        run:  docker build -f Dockerfile -t tictactoeserver .
      
      - name: Run Docker container 
        run: 
          
            docker run -p 8080:8080 -p 8081:8081 tictactoeserver

  run_container:
    runs-on: ubuntu-latest
    steps:
      - name: Run Docker container 
        run: 
          
            docker run -p 8080:8080 -p 8081:8081 tictactoeserver

  test:
      needs: build_container
      runs-on: ubuntu-latest

      steps:
        

        - name: Install dependencies
          run: dart pub get
        

        - name: Run tests
          run: dart test test/server_test.dart

        - name: Stop Docker container
          run : docker stop tictactoeserver
      concurrency:
        group: test-and-run_container
        cancel-in-progress: true
    
  deploy:
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Mohamed Amine Tlili"
          git config --global user.email "foxweb585@gmail.com"

      - name: Push to GitHub
        run: |
          git checkout develop
          git add .
          git commit -m "8th"
          git push
 