name: Dart Test

on:
  push:
      

jobs:
  
     

 
      

  test:
      runs-on: ubuntu-latest

      steps:
        - uses: dart-lang/setup-dart@v1
        - uses: actions/checkout@v3
       
        - name: Build game Container
          run:  docker build  -t gameserver .   
 
        - name: Run Container
        
          
          run: docker run -p 8080:8080  gameserver &
          shell: bash
        - name: Wait for Container
        
          
          run: sleep 15
          shell: bash


        - name: Install dependencies
          run: dart pub get
        

      


        - name: Run tests 
          run: dart test test/server_test.dart
          
            
         
 

        

        
     
    
 
  