name: Dart Test

on:
  push:
    branches:
      - develop  # Adjust the branch name as needed

jobs:
  
     

 
      

  test:
      runs-on: ubuntu-latest

      steps:
        - uses: dart-lang/setup-dart@v1
        - uses: actions/checkout@v3
       
        - name: Build Docker
          run:  docker build  -t tictactoeserver .       
        
        - name: Run Docker container 
        
          
          run: BG_PID=$! docker run -p 8080:8080 -p 8081:8081 tictactoeserver &
          shell: bash


        - name: Install dependencies
          run: dart pub get
        

        - name: Run tests
          run: dart test test/server_test.dart

        

        
     
    
  deploy:
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Mohamed Amine Tlili"
          git config --global user.email "foxweb585@gmail.com"

          git 

      - name: Push to GitHub
        run: |
         git init
         git add .
         git commit -m "first commit"
         git branch -M main
         git remote add origin https://github.com/mohamedamine585/sd.git
         git branch develop
         git checkout develop
         git git push --set-upstream origin develop
      - name: Deploy
        if: success()
        run: ./deploy.sh
 