name: Dart Test

on:
  push:
    branches:
      - feature  # Adjust the branch name as needed

jobs:
  
     

 
      

  test:
      runs-on: ubuntu-latest

      steps:
        - uses: dart-lang/setup-dart@v1
        - uses: actions/checkout@v3
       
        - name: Build Docker
          run:  docker build  -t tictactoeserver .       
        
        - name: Run Docker container 

          run: docker run -p 8080:8080 -p 8081:8081 tictactoeserver &
        


        - name: Install dependencies
          run: dart pub get
        

        - name: Run tests
          run: dart test test/server_test.dart

        - name : Stop Container
          run : docker stop tictactoeserver

        
     
    
  deploy:
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Mohamed Amine Tlili"
          git config --global user.email "foxweb585@gmail.com"

      - name: Push to GitHub
        run: |
          git checkout develop
          git add .
          git commit -m "8th"
          git push
 